In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array((1,2,3,4))
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [2]:
print(a)
print(b)
print(c)

[1 2 3 4]
[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
c.shape

(3, 4)

In [4]:
c.shape=(2,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
d=c.reshape((1,12))
c[1][1]=100
print(c)
print(d)

[[  1   2   3   4   5   6]
 [  7 100   9  10  11  12]]
[[  1   2   3   4   5   6   7 100   9  10  11  12]]


In [6]:
print(c.dtype)

int32


In [7]:
e=np.array([2,3.5,4,5],dtype=int)
f=np.array([2,3.5,4,5],dtype=float)
print(e)
print(f)

[2 3 4 5]
[2.  3.5 4.  5. ]


In [8]:
[key for key,value in np.typeDict.items() if value is np.float64]

['double', 'd', 12, 'float64', 'Float64', 'f8', 'float_', 'float']

numpy ndarray对象元素数据类型包括以下：

In [9]:
set(np.typeDict.values())

{numpy.bool_,
 numpy.bytes_,
 numpy.clongdouble,
 numpy.complex128,
 numpy.complex64,
 numpy.datetime64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.int16,
 numpy.int32,
 numpy.int64,
 numpy.int8,
 numpy.intc,
 numpy.longdouble,
 numpy.object_,
 numpy.str_,
 numpy.timedelta64,
 numpy.uint16,
 numpy.uint32,
 numpy.uint64,
 numpy.uint8,
 numpy.uintc,
 numpy.void}

In [10]:
for i in np.arange(0,0.5,0.1):
    print(i)

0.0
0.1
0.2
0.30000000000000004
0.4


In [11]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

用linspace创建等差数组，第三个参数表示数组元素个数，endpoint：设置是否包括终值。

In [13]:
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

用logspace创建等比数组,base：基数设置，默认为10，endpoint：设置是否包括终值。

In [17]:
np.logspace(0,1,12,base=2,endpoint=False)

array([1.        , 1.05946309, 1.12246205, 1.18920712, 1.25992105,
       1.33483985, 1.41421356, 1.49830708, 1.58740105, 1.68179283,
       1.78179744, 1.88774863])

zeros()、ones()、full()三个函数用来创建指定形状和类型的数组，zeros元素全为0，ones元素全为1，full元素用指定元素补满

In [24]:
a = np.zeros((2,3),np.int)
b = np.ones((2,2),np.int)
c = np.full((2,4),np.pi)
print(str(a)+ '\n' + str(b) + '\n' + str(c))

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


zeros_like(),ones_like(),full_like()三个函数用来创建和目标数组形状、类型相同的数组，zeros_like(a)和zeros_like(a.shape,a.dtype)效果相同。

In [30]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

fromstring()：复制字符串序列创建数组，np.int8表示数组元素类型为八位整型，数组元素对于字符的ASCLL编码。
frombuffer()：使用原字符串内存创建数组，由于字符串是只读的，所以创建的数组无法更改内容。
fromfile()：从文件创建数组。

In [6]:
s='abcdef'
np.fromstring(s,dtype=np.int8)

<ipython-input-6-7c379d13d13f>:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s,dtype=np.int8)


array([ 97,  98,  99, 100, 101, 102], dtype=int8)

fromfunction()：用函数创建数组，第一个参数为引用函数，第二个参数为数组形状，如下数组中每个元素a[i][j]=fun(i,j)

In [7]:
def fun(i,j):
    return((i+1)*(j+1))
np.fromfunction(fun,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

数组切片引用只引用原数组视图，切片和原数组使用相同的存储空间。

In [9]:
a = np.arange(0,10)
b=a[3:7]
a[3:5]=100,101
print(a)
print(b)

[  0   1   2 100 101   5   6   7   8   9]
[100 101   5   6]


numpy除了支持切片操作提取下标元素外还支持整数列表、整数数组、布尔数组等高级下标存取方法。
使用整数列表下标提取元素时，以列表中每个元素为下标，创建的数组不与原数组共享内存。

In [16]:
c=a[[3,3,1,8]]
print(c)
c[2]=200
print(c)
print(a)

[100 100   1   8]
[100 100 200   8]
[  0   1   2 100 101   5   6   7   8   9]


使用整数数组作为下标创建新数组时，新数组的形状和所使用的整数数组相同，创建的新数组不与原数组共享内存。

In [18]:
d = a[np.array([3,3,1,8])]
print(d)
d[2]=200
print(d)
print(a)

[100 100   1   8]
[100 100 200   8]
[  0   1   2 100 101   5   6   7   8   9]


使用布尔数组作为下标创建新数组时，只提取布尔数组中元素为True下标对应的原数组元素。创建的新数组不与原数组共享内存。
只可以使用布尔数组作为下标，不能使用布尔列表。

In [25]:
x = np.arange(0,5,1)
print(x)
y = x[np.array([True,False,True,False,True])]
print(y)
y[2]=100
print(y)
print(x)

[0 1 2 3 4]
[0 2 4]
[  0   2 100]
[0 1 2 3 4]


使用slice()函数创建切片对象。

In [27]:
e = np.arange(0,60,10).reshape(-1,1) + np.arange(0,6)
print(e)
idx = slice(None,None,2),slice(2,None)
f = e[idx]
print(f)
g = e[idx][idx]
print(g)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[ 2  3  4  5]
 [22 23 24 25]
 [42 43 44 45]]
[[ 4  5]
 [44 45]]


使用numpy的_s对象创建数组下标的切片对象。

In [28]:
np.s_[::2,2:]

(slice(None, None, 2), slice(2, None, None))

使用dtype()创建dtype()对象，参数为描述结构类型的字典。字典有两个键：names和formats，每个键对应一个列表，names定义字段名称，formats定义字段类型。

In [34]:
persontype = np.dtype({'names':['name','age','weight'],'formats':['S30','i','f']},align = True)
a = np.array([('wang',32,75.5),('zhang',24,64.5)],dtype = persontype)
print(a)
print(a[0])
print(a['age'])
print(a[0]['name'])

[(b'wang', 32, 75.5) (b'zhang', 24, 64.5)]
(b'wang', 32, 75.5)
[32 24]
b'wang'


tofile(),tostring()可任意将数组以二进制形式转化为字符串或写入文件。

In [35]:
a.tofile('numpy2-1.bin')

使用nditer()函数迭代numpy数组对象。
更改数组存储方式为‘F’列方式。'F':Fortran order，即是列序优先；C order，即是行序优先；

In [21]:
b = np.arange(1*2*3).reshape(1,2,3)
print(b)
print(b.flags)
for i in np.nditer(b):
    print(i)
print('\t')
for j in np.nditer(b.T):
    print(j)
print('\t')
for k in np.nditer(b.copy(order='F')):
    print(k)

[[[0 1 2]
  [3 4 5]]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

0
1
2
3
4
5
	
0
1
2
3
4
5
	
0
3
1
4
2
5


In [ ]:
nditer()函数还有参数op_flags用来指定输出的迭代对象读取方式，可选方式有只读（read-only），只写（writeonly），读写模式（readwrite）

In [38]:
a = np.arange(3*4).reshape(3,4)
print(a)
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*2
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


使用tile()平铺函数可以将narray数组沿各轴平铺，tile()函数第一个参数为平铺对象，第二个参数为各轴重复次数。

In [18]:
a = np.array([[1,2],[3,4]])
b = np.tile(a,(3,3))
b

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])