In [9]:
import numpy as np
a = np.arange(3*4*5).reshape(3,4,5)
lidx = [[0],[1]]
aidx = np.array(lidx)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


列表当作下标

In [13]:
print(type(lidx))
print(a[lidx])
print(a[([0],[1])]) 

<class 'list'>
[[5 6 7 8 9]]
[[5 6 7 8 9]]


<ipython-input-13-b95cdcd1bfc8>:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(a[lidx])


数组当作下标

In [8]:
print(type(aidx))
print(a[aidx])

<class 'numpy.ndarray'>
[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]]]]


### 整数数组作为下标

In [20]:
i0 = np.array([[1,2,1],[0,1,0]])
i1 = np.array([[[0]],[[1]]])
i2 = np.array([[[2,3,2]]])
b = a[i0,i1,i2]
b

array([[[22, 43, 22],
        [ 2, 23,  2]],

       [[27, 48, 27],
        [ 7, 28,  7]]])

#### 步骤如下：
    1、i0.shape=(2,3),i1.shape=(2,1,1),i2.shape=(1,1,3),先将i0，i1，i2按照每轴最大广播为相同形状数组(2,2,3)，广播后的数组如下：

In [21]:
i0,i1,i2

(array([[1, 2, 1],
        [0, 1, 0]]),
 array([[[0]],
 
        [[1]]]),
 array([[[2, 3, 2]]]))

In [22]:
ind0,ind1,ind2 = np.broadcast_arrays(i0,i1,i2)
ind0,ind1,ind2

(array([[[1, 2, 1],
         [0, 1, 0]],
 
        [[1, 2, 1],
         [0, 1, 0]]]),
 array([[[0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 1, 1]]]),
 array([[[2, 3, 2],
         [2, 3, 2]],
 
        [[2, 3, 2],
         [2, 3, 2]]]))

    2、对于任意的b[i,j,k]元素，b[i,j,k]=a[ind0[i,j,k],ind1[i,j,k],ind2[i,j,k]]

In [24]:
print(b[1,1,2])
print(a[ind0[1,1,2],ind1[1,1,2],ind2[1,1,2]])

7
7


    特殊情况：存在切片下标时，此时结果数组的shape属性为：将原数组中shape属性中整数数组占据部分替换为它们的广播之后的shape属性，切片位置的shape属性用切片长度替换。

In [30]:
c = a[1:3,i0,i1]
print(c.shape)
c

(2, 2, 2, 3)


array([[[[25, 30, 25],
         [20, 25, 20]],

        [[26, 31, 26],
         [21, 26, 21]]],


       [[[45, 50, 45],
         [40, 45, 40]],

        [[46, 51, 46],
         [41, 46, 41]]]])

In [29]:
inp0,inp1 = np.broadcast_arrays(i0,i1)
print(inp0.shape,inp1.shape)
inp0,inp1

(2, 2, 3) (2, 2, 3)


(array([[[1, 2, 1],
         [0, 1, 0]],
 
        [[1, 2, 1],
         [0, 1, 0]]]),
 array([[[0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 1, 1]]]))

    对于任意的c[:,i,j,k]=a[1:3,inp0[i,j,k],inp1[i,j,k]].

In [32]:
i,j,k = 1,0,1
print(c[:,i,j,k])
print(a[1:3,inp0[i,j,k],inp1[i,j,k]])

[31 51]
[31 51]


    当切片数组不连续时，结果数组的形状为整数数组广播之后的形状后添加切片元素对于形状。

In [33]:
d = a[i0,:,i1]
print(d.shape)
d

(2, 2, 3, 4)


array([[[[20, 25, 30, 35],
         [40, 45, 50, 55],
         [20, 25, 30, 35]],

        [[ 0,  5, 10, 15],
         [20, 25, 30, 35],
         [ 0,  5, 10, 15]]],


       [[[21, 26, 31, 36],
         [41, 46, 51, 56],
         [21, 26, 31, 36]],

        [[ 1,  6, 11, 16],
         [21, 26, 31, 36],
         [ 1,  6, 11, 16]]]])

    对于任意的d[i,j,k,:] = a[inp0[i,j,k],:,inp1[i,j,k]].

In [35]:
i,j,k = 1,1,1
print(d[i,j,k,:])
print(a[inp0[i,j,k],:,inp1[i,j,k]])

[21 26 31 36]
[21 26 31 36]
