## numpy.random模块

![图片](2.4.1.png)

<img scr="2.4.1.png">

<img scr = "2.4.1.png" >

rand()产生0~1之间的随机浮点数，参数为数组形状；<br/>
randn()产生标准正态分布的随机数，参数为数组形状；<br/>
random()产生指定范围的随机整数，第一，二个参数表示起始值和终值（不包括），第三个参数表示形状。<br/>

In [3]:
import numpy as np
from numpy import random as nr
np.set_printoptions(precision = 2) #设置精度，显示小数点后两位数字
r1 = nr.rand(4,3)
r2 = nr.randn(4,3)
r3 = nr.randint(0,10,(4,3))
r1,r2,r3

(array([[0.  , 0.33, 0.07],
        [0.8 , 0.9 , 0.55],
        [0.83, 0.99, 0.51],
        [0.86, 0.52, 0.9 ]]),
 array([[-0.67,  0.54, -0.63],
        [-1.19,  0.34, -0.07],
        [-0.59,  0.82, -0.39],
        [-0.98,  0.97,  0.71]]),
 array([[2, 1, 9],
        [4, 5, 0],
        [1, 9, 1],
        [7, 7, 3]]))

normal():产生正态分布随机数的数组，前两个参数分别表示期望值和标准差；<br/>
uniform():产生均匀分布随机数的数组，前两个参数表示范围；<br/>
poisson():产生泊松分布随机数的数组，第一个参数指定λ参数，表示单位时间（或单位面积）内随机事件的平均发生率，由于泊松分布是离散分布，因此它的输出为一个整数数组。<br/>
这几个函数最后一个参数表示生成数组的形状。

In [6]:
r4 = nr.normal(100,10,(4,3))
r5 = nr.uniform(10,20,(4,3))
r6 = nr.poisson(2.0,(4,3))
r4,r5,r6

(array([[ 77.1 , 102.5 ,  98.87],
        [119.63,  96.47,  87.51],
        [ 88.45,  85.27, 102.22],
        [ 89.27, 102.69, 106.47]]),
 array([[14.53, 14.84, 17.55],
        [14.67, 15.95, 18.16],
        [13.54, 16.82, 16.54],
        [15.72, 10.46, 11.47]]),
 array([[4, 2, 3],
        [2, 4, 2],
        [0, 2, 3],
        [0, 0, 0]]))

    permutation()用于产生乱序数组，参数为整数n时，返回[0,n)这几个整数的随机排列，当参数为序列时，返回该序列元素随机排列之后的序列。<br/>
    permutation()返回一个新的数组，shuffle()直接将原数组打乱顺序。

In [15]:
a = np.arange(0,50,10)
print(nr.permutation(10))
print(nr.permutation(a))
nr.shuffle(a)
print(a)

[8 9 1 0 7 2 5 3 6 4]
[10 20  0 30 40]
[ 0 40 20 10 30]
